version: "3"
services:

  cassandra:
    container_name: cassandra
    image: cassandra:3.11
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 5s
      retries: 60
    networks:
      - default-network
    ports:
      - 9042:9042

  postgres:
    container_name: postgres
    image: postgres:12.3
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 3s
      retries: 3
    restart: always
    networks:
      - default-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_WALDIR: /pg_waldir
      PGDATA: /pg_data
    ports:
      - 5432:5432

networks:
  default-network:
    driver: bridge
